### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by Korusuke**
Change jderobot.org/ to wiki.jderobot.org/

Also Fixed Previous GSoC project link of @pankhurivanjani 

Sorry for the removal of blank spaces...my VS Code is configured to remove them as they were not acceptable in my last year's org.

Should I update this PR without white space changes or is this fine?

### CODE REVIEW

**Comment by igarag** [comment]
Hi @Korusuke.

It would not be necessary to change all the blank spaces it in all files but since in this case those small corrections have been on one file there is no problem. Clean code is always welcome :+1: 

Thanks.

**Comment by Korusuke** [comment]
Hey @igarag,

Thanks for approving the PR. 
I see that you have closed the PR but haven't merged it, any specific reason?

**Comment by igarag** [comment]
Sorry, no it was just an error.

Now is merged.

Regards.

**Comment by Korusuke** [comment]
Oh, Ok.

Thanks for merging. Looking forward to contributing more.

**Pull request merged**
